### ISSUE TITLE
failed importing json file, connectors not working

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1058] opened 2021-02-04 17:59 UTC
OS: Ubuntu 20
OpenCTI latest version, running on docker

I need you guys help. I managed to install and run the latest OpenCTI in docker.
I can see the dashboard but so far I can't make use of it - all blank.
I tried to import (IoC) json file manually but failed. (see screen shot)

![image](https://user-images.githubusercontent.com/20463433/106934645-5cc82b00-66e8-11eb-8bb9-1fc684cd1ecd.png)

None of the connectors I tried work (misp, virustotal, alienvault, cybercrime-tracker)

**Comment by SamuelHassine** [comment] 2021-02-05 11:38
Hello @NetEyes,

Can you please check the errors you have in the connector "ImportFileStix2" page?

![image](https://user-images.githubusercontent.com/1334279/107029273-0d006700-67af-11eb-848c-04b3e0ffa23d.png)

Kind regards,
Samuel

**Comment by NetEyes** [comment] 2021-02-06 20:42
I don't see the actual error on the page. 
![image](https://user-images.githubusercontent.com/20463433/107129210-c9325e00-6891-11eb-9710-36027ec7a2f8.png)
![image](https://user-images.githubusercontent.com/20463433/107129224-e6672c80-6891-11eb-8f6c-ae26c56a090b.png)
![image](https://user-images.githubusercontent.com/20463433/107129228-f4b54880-6891-11eb-901d-01545ba6f3a7.png)

**Comment by manonviallet** [comment] 2021-07-08 14:48
Good afternoon @NetEyes, is your problem still active or did you manage to solve it ?

**Comment by manonviallet** [comment] 2021-07-27 08:48
Hello, since there has been no further answer on this page, I will close this issue. However, don't hesitate to open it back if the problem is still valid, or to open a new one if you have met additional difficulties. Don't hesitate to join us on the Slack Channel of Luatix to discuss with the community !

**Closed as completed by manonviallet** 2021-07-27 08:48 UTC
Labels: question, solved
