### ISSUE TITLE
Dates should not always be required

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#501] opened 2020-02-18 14:52 UTC
## Description
Dates are requested for all relations, however in some cases they should not be mandatory or should be replaced by a "always true" type of attribute :
- for "localised in" relations (for instance, a company is localised in a country, or a city in a country)
- linked to : for instance a link between two campaigns does not necessary needs to be dated.

**Comment by SamuelHassine** [comment] 2020-05-27 15:16
Hello @amr-cossi,

I know that the "always-displayed" first_seen and last_seen can be awkward in some situations. The problem is in "some cases", it could be useful to have the date, even for a company located in a country or a city.

The solution currently implemented (pre-filled dates with the today's date) seems to be enough just to ignore that fields. It seems to be really difficult to display this field only in the some situations and to not display in it others. 

I close this issue for the moment, if someone have a better solution/idea, feel free to re-open and explain it.

**Comment by SamuelHassine** [comment] 2020-05-27 20:00
After a discussion, we are able to implement the fact that all first_seen and last_seen will be optional in every relations. It will be implemented in the next release.

**Closed as completed** 2020-09-03 19:43 UTC
Labels: feature, solved
