### ISSUE TITLE
Cannot massively tag IoCs

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#807] opened 2020-07-27 14:19 UTC
# Description

It is not possible to tag many IoCs with the same tag

# Environment
	1. OS :  Debian 4.9.82-1+deb9u3 (2018-03-02)
	2. OpenCTI version: 3.2.2
	3. OpenCTI client: Platform

# Expected Output

To be able to select all the IoCs and tag them all at the same time
 
# Actual Output 

 Add tag one by one

**Comment by richard-julien** [comment] 2021-03-26 08:23
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/771

**Closed as completed by richard-julien** 2021-03-26 08:23 UTC
Labels: duplicate, feature
