### ISSUE TITLE
Add multi-select/select all delete record function 

### ISSUE THREAD

**Issue by A1oha** [OpenCTI-Platform/opencti#1200] opened 2021-03-26 02:35 UTC
## Problem to Solve

Sometimes, there may be false positives in TI collected from a certain data source or time interval. When I filter them out, I cannot select multiple records and delete them all at once. 

## Current Workaround

Delete the filtered records one by one.

## Proposed Solution

1.Add multiple selection function；
2.Increase the select all function；
3.Add delete function.

## Additional Information

![image](https://user-images.githubusercontent.com/40291952/112568635-bbbf3c00-8e1d-11eb-8d60-5c63fe2e51ac.png)

**Comment by richard-julien** [comment] 2021-03-26 08:22
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/771

**Closed as completed by richard-julien** 2021-03-26 08:22 UTC
Labels: duplicate, feature
