### ISSUE TITLE
Support for stix2 infrastructure domain objects

### ISSUE THREAD

**Issue by jurelou** [OpenCTI-Platform/opencti#631] opened 2020-04-18 10:42 UTC
## Problem to Solve

Support for stix2 infrastructure domain objects.

can i know if such an addition is planned? otherwise if you give me some hints to do it, I can carry out the development of this functionality

## Current Workaround
None (to my knowledge)

## Proposed Solution

Add an entity `Infrastructure` to the data model

## Additional Information

Stix2 infrastructure domain object: https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_jo3k1o6lr9
Examples of stix2 infrastructure schemas: https://github.com/oasis-open/cti-stix2-json-schemas/blob/master/examples/infrastructure.json

**Comment by richard-julien** [comment] 2020-04-18 11:20
Hi @jurelou, thanks for the ticket and the help proposal. Looks like duplicate of https://github.com/OpenCTI-Platform/opencti/issues/387
Will come back to you after we start it.

**Comment by richard-julien** [comment] 2020-04-18 11:20
Closing the ticket, continue the discussion in https://github.com/OpenCTI-Platform/opencti/issues/387

**Closed as completed by richard-julien** 2020-04-18 11:20 UTC
Labels: duplicate, feature
