### ISSUE TITLE
Refactor of routing

### ISSUE THREAD

**Issue by Kedae** [OpenCTI-Platform/opencti#2797] opened 2023-02-01 10:27 UTC
We have multiple issues regarding our handle of routing. We need to use the nested capability of react-router to clear some re-render that are useless because nested routes change

Ressources : [v5 to V6](https://reactrouter.com/en/main/upgrading/v5)

**Comment by nino-filigran** [comment] 2024-03-25 10:14
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/6303

**Closed as completed by nino-filigran** 2024-03-25 10:14 UTC
Labels: duplicate, feature, technical improvement
