### ISSUE TITLE
Be able to change a relation type or an entity type after creation

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1396] opened 2021-06-04 13:02 UTC
## Problem to Solve

Sometime, the analyst create an entity or a relation and realize afterwards that the type of the entity or the type of the relation is not the good one. Today, there is no other choices but to suppress the relation or the entity and to create a new one from scratch. This can be tedious, as it is not possible to easily copy-paste the information (description, dates, author, etc.). Several possibilities seems to be available, depending on the type of object:
- for relations, during modification, it should be possible to have a scrolling menu offering to change the type of relation or its direction while keeping all the other fields filled ;
- for entities:
      - one solution could be to be able to change the type of the entity through a scrolling menu. This could come with a warning indicating that some fields are going to be changed, and that all relations linked to this entity are going to be modified. They could be changed by default to "related-to" or a prompt window could pop-up to allow the user to manually change each type of relation (or tick a box saying "change all to "related-to" ") ;
      - it could also be done by allowing to merge different type of entities from the data curation tab (for instance, merge a organisation and a threat actor, merge an incident with an organisation, an incident and a campaign etc.)

**Comment by securitiz** [comment] 2023-07-15 17:53
Following up here, it would be useful to be able to merge two objects of different types, in specific cases:

- Threat Actor & Intrusion Set
- Malware & Tool

**Comment by Jipegien** [comment] 2023-07-27 15:02
duplicate of #3571

**Closed as not planned by Jipegien** 2023-07-27 15:02 UTC
Labels: duplicate, feature
