### ISSUE TITLE
Workspace "Entity" section shows "No available options" but there are many entities ingested

### ISSUE THREAD

**Issue by maddiesolz** [OpenCTI-Platform/opencti#815] opened 2020-07-27 18:09 UTC
## Description

{ Workspace "Entity" section shows "No available options" but there are many entities ingested }

## Environment

1. OS (where OpenCTI server runs): { Ubuntu 18.04.4 }
2. OpenCTI version: { e.g. OpenCTI 3.3.2 }
3. OpenCTI client: { frontend }
4. Other environment details: { Ubuntu VM on 5.3.0-1032-azure }

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { Click Workpaces}
2. { Create Test Workspace, TLP White }
3. { Click + to add widget }
4. { Add name and select widget }
5. { Attempt to select Entity, no available entities }
6. { There are over 700k entities according to primary dashboard }

## Expected Output

{ List the 700k+ entities }

## Actual Output

{ "No available entities" }
 
## Additional information

{ Screenshots attached }

![image](https://user-images.githubusercontent.com/2287075/88575936-425f1780-d00a-11ea-8a2b-494ae255d9c1.png)
![image](https://user-images.githubusercontent.com/2287075/88576259-c6190400-d00a-11ea-81da-926df6884399.png)

**Comment by smclinden** [comment] 2020-07-29 15:48
I don't know if this is related, but this is what I am seeing:

![image](https://user-images.githubusercontent.com/8810661/88822040-6436d680-d191-11ea-8dd4-c94e8ebe0e74.png)

**Comment by maddiesolz** [comment] 2020-08-04 13:59
I am not sure what that page is. The page I am referring to is the button above that one, the one that looks like a compass (workspaces).

**Comment by SamuelHassine** [comment] 2020-12-15 23:58
Cllosing, duplicate of #307.

**Closed as completed by SamuelHassine** 2020-12-15 23:58 UTC
Labels: bug, duplicate
