### ISSUE TITLE
Feeds from MISP and others are not ingesting

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1288] opened 2021-04-22 11:39 UTC
Hi,

Fresh install.
OpenCTI v4.4.1
Ubuntu 20.

Using the latest version of OpenCTI and connectors, I am no longer getting feeds from MISP.
From OpenCTI dashboard shows MISP connector and everything is "In Progress" but nothing happening.
Note: same issue on the CVE, Mitre connectors. I'm not sure if this is a connector issue or most likely the OpenCTI itself.

![image](https://user-images.githubusercontent.com/20463433/115707903-4facf680-a33d-11eb-880e-04472dce6cc7.png)

**Comment by SamuelHassine** [comment] 2021-04-22 11:52
Hello @NetEyes,

Have you any worker running ? Any logs of the worker to share?

**Comment by richard-julien** [comment] 2021-04-22 11:52
Ingestion are done by the workers.
Please check you have connector workers and check the logs of course.

**Comment by NetEyes** [comment] 2021-04-22 11:56
![image](https://user-images.githubusercontent.com/20463433/115710341-3c4f5a80-a340-11eb-88ae-47fb9059e02c.png)

**Comment by NetEyes** [comment] 2021-04-22 11:57
Note: All my connectors are working prior to version 4.4.0

**Comment by richard-julien** [comment] 2021-04-22 12:02
You give the log of the connector and not the worker.

**Comment by NetEyes** [comment] 2021-04-22 12:06
![image](https://user-images.githubusercontent.com/20463433/115711524-9b619f00-a341-11eb-9f9a-420bf14ff76f.png)

**Comment by richard-julien** [comment] 2021-04-22 12:13
Not sure but looks like when you upgrade your rabbitMQ is reset. So now you have a mismatch between the OCTI connectors registration and the reality in rabbitMQ.
So to resolve your current problem.
1. Stop all your connectors and workers
2. Go in OpenCTI UI and delete all connectors
3. Stop everything
4. Clean your rabbitMQ -> And configure correctly the storage to not reproduce a cleanup in your next upgrade
5. Restart everything

**Comment by NetEyes** [comment] 2021-04-22 12:16
Note: What I did. I restored the baseline backup to clean Ubuntu 20.0.4 and install fresh OpenCTI 4.4.1. 
I can repeat this process again and will let you know.

**Comment by NetEyes** [comment] 2021-04-22 13:00
This is now a fresh install of OpenCTI v4.4.1 with Ubuntu 20.0.4 (with MISP defined in docker-compose.yml)

worker logs
![image](https://user-images.githubusercontent.com/20463433/115717507-3d848580-a348-11eb-9a54-eed391924cc3.png)

![image](https://user-images.githubusercontent.com/20463433/115717652-60169e80-a348-11eb-888b-e61c565226dd.png)

DOCKER COMPOSE FILE ...

![image](https://user-images.githubusercontent.com/20463433/115717779-80465d80-a348-11eb-9264-c69112451ead.png)
![image](https://user-images.githubusercontent.com/20463433/115717867-981de180-a348-11eb-995b-dbb5c4752ea5.png)
![image](https://user-images.githubusercontent.com/20463433/115717981-b4218300-a348-11eb-9617-555f2c5932a5.png)
![image](https://user-images.githubusercontent.com/20463433/115718144-db785000-a348-11eb-8056-2805a5a94cf6.png)
![image](https://user-images.githubusercontent.com/20463433/115718224-eaf79900-a348-11eb-8b6c-79070842fe6f.png)

DOCKER .env

![image](https://user-images.githubusercontent.com/20463433/115718519-2e520780-a349-11eb-945a-6e27d27ebfa3.png)

**Comment by djds** [comment] 2021-04-25 06:03
Try setting the `hostname` key for the `rabbitmq` service in `docker-compose.yml`. RabbitMQ derives the node name from the system hostname by default, and if running in a container, that will be [the container's ID in Docker](https://docs.docker.com/config/containers/container-networking/#ip-address-and-hostname), which will change on container redeployment. The persistent data is stored in a subdirectory of the `mnesia` directory, which will correspond to the RabbitMQ user and node name, so by default this will be something like:

```sh
docker run -v "${PWD}/rabbitmq:/var/lib/rabbitmq:rw" rabbitmq:3-management-alpine; ls -1 "${PWD}/rabbitmq/mnesia"
<snipped>
rabbit@2dee8673dded
rabbit@2dee8673dded-feature_flags
rabbit@2dee8673dded-plugins-expand
```
Whereas setting the hostname to `predictable` results in the following:

```sh
docker run --hostname=predictable -v "${PWD}/rabbitmq:/var/lib/rabbitmq:rw" rabbitmq:3-management-alpine; ls -1 "${PWD}/rabbitmq/mnesia"
<snipped>
rabbit@predictable
rabbit@predictable-feature_flags
rabbit@predictable-plugins-expand
```

The YAML would be something like
```yaml
---
version: '3.7'
  services:
    rabbitmq:
      hostname: predictable
      image: rabbitmq:3-management-alpine
      volumes:
      - ./rabbitmq:/var/lib/rabbitmq:rw
```

**Comment by NetEyes** [comment] 2021-04-26 17:29
Tried the suggestion but still not working.
Note. This is a fresh install on fresh Ubuntu server 20.  We have another Ubuntu (20.0.4 LTS) with OpenCTI that is currently working prior to version 4.4.0.

**Comment by andrewnorthern** [comment] 2021-05-14 17:30
I am experiencing the same issue.

**Comment by sreemanshanker** [comment] 2021-06-25 01:44
i am experiencing the exact same issue as well. Loaded fine the first round - never updated after. Looked into the worker logs and its the same as the pictures above - unable to connect to openCTI

**Comment by PandaLyfe** [comment] 2021-10-13 14:41
I'm experiencing the same issue in version  5.0.1.

**Comment by LaZyDK** [comment] 2021-11-22 07:06
I am seeing the same on 5.0.3

**Comment by richard-julien** [comment] 2021-11-26 11:11
Hi all. Not sure to really understand what is the "same issue" here because this ticket contains 2 different issues.

1. Deleted/Reset RabbitMQ that lead to error in the workers. For this case you need to stop all workers and all connectors, remove all referenced connectors in OPENCTI and then restart the connectors and  the workers.

2. Communication problem between workers and OpenCTI in docker environment. For this problem you need to be sure that your docker network between containers are correctly defined. If you starting your container with docker-run command you NEED to define a network that all containers can access.

I close this ticket for now because i think the initial question was resolved.

Base on my response if its not working for you please create a specific ticket with correct logs.

**Closed as completed by richard-julien** 2021-11-26 11:11 UTC
Labels: question, solved
