### ISSUE TITLE
Cannot export some reports

### ISSUE THREAD

**Issue by khalid1515** [OpenCTI-Platform/opencti#276] opened 2019-10-21 10:16 UTC
i am having an issue with the latest release, 

currently some reports cannot be exported as when i try to export them i get 
(generating report in progress..) 

it is stuck on this state, even when i tried to restart the whole vm and relaunch docker again the (in progress message) still appears. 

you support is highly appreciated.

**Comment by SamuelHassine** [comment] 2019-10-25 05:04
Hello @khalid1515,

The issue is now fixed in 2.0.0.

**Closed as completed by SamuelHassine** 2019-10-25 05:04 UTC
Labels: bug, solved
