### ISSUE TITLE
Number of operations complete is larger than the total number of operations

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/opencti#1523] opened 2021-07-20 03:48 UTC
Hello! @SamuelHassine 
## Description
On the web page of the connector's status, after the connector has completed one progress, the statistics are wrong. The number of operations complete is larger than the total number of operations.
![image](https://user-images.githubusercontent.com/68931768/126258895-8f48c3d7-3cdf-4d13-95f5-349ed3e4223a.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server LTS 20.04
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend

## Expected Output

The number of operations complete should be less than or equal to the total number of operations.

## Actual Output

The number of operations complete is larger than the total number of operations.
 
Thanks for your help!

**Comment by SamuelHassine** [comment] 2021-08-16 20:19
Hello @Ken-Abruzzi, 

This is more likely a platform problem. I will take a look with @richard-julien.

Kind regards,
Samuel

**Comment by sukesh-ak** [comment] 2021-09-11 12:19
So when connector processing is disrupted, I believe its creating a new entry but the count increase is still being done on the initial entry which has a status of "Completed"

So progress count increase happening in the completed status instead of the new ones. Thats what I believe the issue is. Should be same for other connectors I guess but its more visible on Alienvault because of too many pulses coming in. 

![image](https://user-images.githubusercontent.com/53081362/132947589-eb69a8c3-21a4-4c51-a8ef-de0648f131ab.png)

**Comment by Ken-Abruzzi** [comment] 2021-09-14 03:31
> So when connector processing is disrupted, I believe its creating a new entry but the count increase is still being done on the initial entry which has a status of "Completed"
> 
> So progress count increase happening in the completed status instead of the new ones. Thats what I believe the issue is. Should be same for other connectors I guess but its more visible on Alienvault because of too many pulses coming in.
> 
> ![image](https://user-images.githubusercontent.com/53081362/132947589-eb69a8c3-21a4-4c51-a8ef-de0648f131ab.png)

I only observe this phenomenon in the alienvault connector. And there is another phenomenon that sometimes the progress bar of some connetors (not only alienvault connector) will be stuck there with only 1 operation left.

**Comment by SamuelHassine** [comment] 2021-11-20 15:45
Should be fixed in 5.0.4. Please tell us if you still have the problem and open a new issue.

Thanks!

**Closed as completed by SamuelHassine** 2021-11-20 15:45 UTC
Labels: bug, solved
