### ISSUE TITLE
Broken zoom on some big reports

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#486] opened 2020-02-12 14:32 UTC
## Description

For big reports (reports with many entities and links) which have been capitalized, the zooming function seems to be broken, which prevents the user from correctly visualising knowledge in the graph and from beeing able to edit it.

## Reproducible Steps

It can be visible in the demo on some reports for instance on the Maze report https://demo.opencti.io/dashboard/reports/all/d999f711-aec1-4d1a-9579-2164e3468cb7/knowledge
(see capture below)

## Expected Output

Be able to zoom and navigate on those reports like any other

## Actual Output

The report can be displayed bu all links and entities are so small they cannot be seen.

**Comment by I-Iugo** [comment] 2020-03-19 14:40
@SamuelHassine , @richard-julien Same issue to [https://demo.opencti.io/dashboard/reports/all/5ce6e3c5-e7bc-4ba3-8037-6e9f173d8be5/knowledge](https://demo.opencti.io/dashboard/reports/all/5ce6e3c5-e7bc-4ba3-8037-6e9f173d8be5/knowledge)

## Expected Output

Ability to zoom in

## Actual Output

Cannot zoom in

**Comment by SamuelHassine** [comment] 2020-12-15 23:57
Closing this one, duplicate of #504.

**Closed as completed by SamuelHassine** 2020-12-15 23:57 UTC
Labels: bug, duplicate
